export type TDeal = {
    ADDITIONAL_INFO: null | string;
    ASSIGNED_BY_ID: string;
    BEGINDATE: string;
    CATEGORY_ID: string;
    CLOSED: string;
    CLOSEDATE: string | Date | null;
    COMMENTS: null | string;
    COMPANY_ID: string;
    CONTACT_ID: null | string;
    CREATED_BY_ID: string;
    CURRENCY_ID: string;
    DATE_CREATE: string;
    DATE_MODIFY: string;
    ID: string;
    IS_MANUAL_OPPORTUNITY: string;
    IS_NEW: string;
    IS_RECURRING: string;
    IS_REPEATED_APPROACH: string;
    IS_RETURN_CUSTOMER: string;
    LAST_ACTIVITY_BY: string;
    LAST_ACTIVITY_TIME: string;
    LEAD_ID: null | string;
    LOCATION_ID: null | string;
    MODIFY_BY_ID: string;
    MOVED_BY_ID: string;
    MOVED_TIME: string;
    OPENED: string;
    OPPORTUNITY: string | null;
    ORIGINATOR_ID: null | string;
    ORIGIN_ID: null | string;
    PARENT_ID_139: null | string;
    PARENT_ID_141: null | string;
    PROBABILITY: null | string;
    QUOTE_ID: null | string;
    SOURCE_DESCRIPTION: null | string;
    SOURCE_ID: null | string;
    STAGE_ID: string;
    STAGE_SEMANTIC_ID: string;
    TAX_VALUE: null | string;
    TITLE: string;
    TYPE_ID: string;
    UTM_CAMPAIGN: null | string;
    UTM_CONTENT: null | string;
    UTM_MEDIUM: null | string;
    UTM_SOURCE: null | string;
    UTM_TERM: null | string;
};
